import herbs from "../image_assets/HerbImageExport"

export const IngredientData = [
    {id: 0, image_normal: herbs[0], image_golden: "ingred1_g.png", amount: 0, discovered: false},
    {id: 1, image_normal: herbs[1], image_golden: "ingred2_g.png", amount: 0, discovered: false},
    {id: 2, image_normal: herbs[2], image_golden: "ingred3_g.png", amount: 0, discovered: false},
    {id: 3, image_normal: herbs[3], image_golden: "ingred4_g.png", amount: 0, discovered: false},
    {id: 4, image_normal: herbs[4], image_golden: "ingred5_g.png", amount: 0, discovered: false},
    {id: 5, image_normal: herbs[5], image_golden: "ingred6_g.png", amount: 0, discovered: false},
    {id: 6, image_normal: herbs[6], image_golden: "ingred7_g.png", amount: 0, discovered: false},
    {id: 7, image_normal: herbs[7], image_golden: "ingred8_g.png", amount: 0, discovered: false},
    {id: 8, image_normal: herbs[8], image_golden: "ingred9_g.png", amount: 0, discovered: false},
    {id: 9, image_normal: herbs[9], image_golden: "ingred10_g.png", amount: 0, discovered: false},

    {id: 10, image_normal: herbs[10], image_golden: "ingred11_g.png", amount: 0, discovered: false},
    {id: 11, image_normal: herbs[11], image_golden: "ingred12_g.png", amount: 0, discovered: false},
    {id: 12, image_normal: herbs[12], image_golden: "ingred13_g.png", amount: 0, discovered: false},
    {id: 13, image_normal: herbs[13], image_golden: "ingred14_g.png", amount: 0, discovered: false},
    {id: 14, image_normal: herbs[14], image_golden: "ingred15_g.png", amount: 0, discovered: false},
    {id: 15, image_normal: herbs[15], image_golden: "ingred16_g.png", amount: 0, discovered: false},
    {id: 16, image_normal: herbs[16], image_golden: "ingred17_g.png", amount: 0, discovered: false},
    {id: 17, image_normal: herbs[17], image_golden: "ingred18_g.png", amount: 0, discovered: false},
    {id: 18, image_normal: herbs[18], image_golden: "ingred19_g.png", amount: 0, discovered: false},
    {id: 19, image_normal: herbs[19], image_golden: "ingred20_g.png", amount: 0, discovered: false},

    {id: 20, image_normal: herbs[20], image_golden: "ingred21_g.png", amount: 0, discovered: false},
    {id: 21, image_normal: herbs[21], image_golden: "ingred22_g.png", amount: 0, discovered: false},
    {id: 22, image_normal: herbs[22], image_golden: "ingred23_g.png", amount: 0, discovered: false},
    {id: 23, image_normal: herbs[23], image_golden: "ingred24_g.png", amount: 0, discovered: false},
    {id: 24, image_normal: herbs[24], image_golden: "ingred25_g.png", amount: 0, discovered: false},
    {id: 25, image_normal: herbs[25], image_golden: "ingred26_g.png", amount: 0, discovered: false},
    {id: 26, image_normal: herbs[26], image_golden: "ingred27_g.png", amount: 0, discovered: false},
    {id: 27, image_normal: herbs[27], image_golden: "ingred28_g.png", amount: 0, discovered: false},
    {id: 28, image_normal: herbs[28], image_golden: "ingred29_g.png", amount: 0, discovered: false},
    {id: 29, image_normal: herbs[29], image_golden: "ingred30_g.png", amount: 0, discovered: false},

    {id: 30, image_normal: herbs[30], image_golden: "ingred31_g.png", amount: 0, discovered: false},
    {id: 31, image_normal: herbs[31], image_golden: "ingred32_g.png", amount: 0, discovered: false},
    {id: 32, image_normal: herbs[32], image_golden: "ingred33_g.png", amount: 0, discovered: false},
    {id: 33, image_normal: herbs[33], image_golden: "ingred34_g.png", amount: 0, discovered: false},
    {id: 34, image_normal: herbs[34], image_golden: "ingred35_g.png", amount: 0, discovered: false},
    {id: 35, image_normal: herbs[35], image_golden: "ingred36_g.png", amount: 0, discovered: false},
    {id: 36, image_normal: herbs[36], image_golden: "ingred37_g.png", amount: 0, discovered: false},
    {id: 37, image_normal: herbs[37], image_golden: "ingred38_g.png", amount: 0, discovered: false},
    {id: 38, image_normal: herbs[38], image_golden: "ingred39_g.png", amount: 0, discovered: false},
    {id: 39, image_normal: herbs[39], image_golden: "ingred40_g.png", amount: 0, discovered: false},

    {id: 40, image_normal: herbs[40], image_golden: "ingred41_g.png", amount: 0, discovered: false},
    {id: 41, image_normal: herbs[41], image_golden: "ingred42_g.png", amount: 0, discovered: false},
    {id: 42, image_normal: herbs[42], image_golden: "ingred43_g.png", amount: 0, discovered: false},
    {id: 43, image_normal: herbs[43], image_golden: "ingred44_g.png", amount: 0, discovered: false},
    {id: 44, image_normal: herbs[44], image_golden: "ingred45_g.png", amount: 0, discovered: false},
    {id: 45, image_normal: herbs[45], image_golden: "ingred46_g.png", amount: 0, discovered: false},
    {id: 46, image_normal: herbs[46], image_golden: "ingred47_g.png", amount: 0, discovered: false},
    {id: 47, image_normal: herbs[47], image_golden: "ingred48_g.png", amount: 0, discovered: false},
    {id: 48, image_normal: herbs[48], image_golden: "ingred49_g.png", amount: 0, discovered: false},
    {id: 49, image_normal: herbs[49], image_golden: "ingred50_g.png", amount: 0, discovered: false},

    {id: 50, image_normal: herbs[50], image_golden: "ingred51_g.png", amount: 0, discovered: false},
    {id: 51, image_normal: herbs[51], image_golden: "ingred52_g.png", amount: 0, discovered: false},
    {id: 52, image_normal: herbs[52], image_golden: "ingred53_g.png", amount: 0, discovered: false},
    {id: 53, image_normal: herbs[53], image_golden: "ingred54_g.png", amount: 0, discovered: false},
    {id: 54, image_normal: herbs[54], image_golden: "ingred55_g.png", amount: 0, discovered: false},
    {id: 55, image_normal: herbs[55], image_golden: "ingred56_g.png", amount: 0, discovered: false},
    {id: 56, image_normal: herbs[56], image_golden: "ingred57_g.png", amount: 0, discovered: false},
    {id: 57, image_normal: herbs[57], image_golden: "ingred58_g.png", amount: 0, discovered: false},
    {id: 58, image_normal: herbs[58], image_golden: "ingred59_g.png", amount: 0, discovered: false},
    {id: 59, image_normal: herbs[59], image_golden: "ingred60_g.png", amount: 0, discovered: false},

    {id: 60, image_normal: herbs[60], image_golden: "ingred61_g.png", amount: 0, discovered: false},
    {id: 61, image_normal: herbs[61], image_golden: "ingred62_g.png", amount: 0, discovered: false},
    {id: 62, image_normal: herbs[62], image_golden: "ingred63_g.png", amount: 0, discovered: false},
    {id: 63, image_normal: herbs[63], image_golden: "ingred64_g.png", amount: 0, discovered: false},
    {id: 64, image_normal: herbs[64], image_golden: "ingred65_g.png", amount: 0, discovered: false},
    {id: 65, image_normal: herbs[65], image_golden: "ingred66_g.png", amount: 0, discovered: false},
    {id: 66, image_normal: herbs[66], image_golden: "ingred67_g.png", amount: 0, discovered: false},
    {id: 67, image_normal: herbs[67], image_golden: "ingred68_g.png", amount: 0, discovered: false},
    {id: 68, image_normal: herbs[68], image_golden: "ingred69_g.png", amount: 0, discovered: false},
    {id: 69, image_normal: herbs[69], image_golden: "ingred70_g.png", amount: 0, discovered: false},
     
    {id: 70, image_normal: herbs[70], image_golden: "ingred71_g.png", amount: 0, discovered: false},
    {id: 71, image_normal: herbs[71], image_golden: "ingred72_g.png", amount: 0, discovered: false},
    {id: 72, image_normal: herbs[72], image_golden: "ingred73_g.png", amount: 0, discovered: false},
    {id: 73, image_normal: herbs[73], image_golden: "ingred74_g.png", amount: 0, discovered: false},
    {id: 74, image_normal: herbs[74], image_golden: "ingred75_g.png", amount: 0, discovered: false},
    {id: 75, image_normal: herbs[75], image_golden: "ingred76_g.png", amount: 0, discovered: false},
    {id: 76, image_normal: herbs[76], image_golden: "ingred77_g.png", amount: 0, discovered: false},
    {id: 77, image_normal: herbs[77], image_golden: "ingred78_g.png", amount: 0, discovered: false},
    {id: 78, image_normal: herbs[78], image_golden: "ingred79_g.png", amount: 0, discovered: false},
    {id: 79, image_normal: herbs[79], image_golden: "ingred80_g.png", amount: 0, discovered: false},

    {id: 80, image_normal: herbs[80], image_golden: "ingred71_g.png", amount: 0, discovered: false},
    {id: 81, image_normal: herbs[81], image_golden: "ingred72_g.png", amount: 0, discovered: false},
    {id: 82, image_normal: herbs[82], image_golden: "ingred73_g.png", amount: 0, discovered: false},
    {id: 83, image_normal: herbs[83], image_golden: "ingred74_g.png", amount: 0, discovered: false},
    {id: 84, image_normal: herbs[84], image_golden: "ingred75_g.png", amount: 0, discovered: false},
    {id: 85, image_normal: herbs[85], image_golden: "ingred76_g.png", amount: 0, discovered: false},
    {id: 86, image_normal: herbs[86], image_golden: "ingred77_g.png", amount: 0, discovered: false},
    {id: 87, image_normal: herbs[87], image_golden: "ingred78_g.png", amount: 0, discovered: false},
    {id: 88, image_normal: herbs[88], image_golden: "ingred79_g.png", amount: 0, discovered: false},
    {id: 89, image_normal: herbs[89], image_golden: "ingred80_g.png", amount: 0, discovered: false},

    {id: 90, image_normal: herbs[90], image_golden: "ingred71_g.png", amount: 0, discovered: false},
    {id: 91, image_normal: herbs[91], image_golden: "ingred72_g.png", amount: 0, discovered: false},
    {id: 92, image_normal: herbs[92], image_golden: "ingred73_g.png", amount: 0, discovered: false},
    {id: 93, image_normal: herbs[93], image_golden: "ingred74_g.png", amount: 0, discovered: false},
    {id: 94, image_normal: herbs[94], image_golden: "ingred75_g.png", amount: 0, discovered: false},
    {id: 95, image_normal: herbs[95], image_golden: "ingred76_g.png", amount: 0, discovered: false},
    {id: 96, image_normal: herbs[96], image_golden: "ingred77_g.png", amount: 0, discovered: false},
    {id: 97, image_normal: herbs[97], image_golden: "ingred78_g.png", amount: 0, discovered: false},
    {id: 98, image_normal: herbs[98], image_golden: "ingred79_g.png", amount: 0, discovered: false},
    {id: 99, image_normal: herbs[99], image_golden: "ingred80_g.png", amount: 0, discovered: false},

    {id: 100, image_normal: herbs[100], image_golden: "ingred71_g.png", amount: 0, discovered: false},
    {id: 101, image_normal: herbs[101], image_golden: "ingred72_g.png", amount: 0, discovered: false},
    {id: 102, image_normal: herbs[102], image_golden: "ingred73_g.png", amount: 0, discovered: false},
    {id: 103, image_normal: herbs[103], image_golden: "ingred74_g.png", amount: 0, discovered: false},
    {id: 104, image_normal: herbs[104], image_golden: "ingred75_g.png", amount: 0, discovered: false},
    {id: 105, image_normal: herbs[105], image_golden: "ingred76_g.png", amount: 0, discovered: false},
    {id: 106, image_normal: herbs[106], image_golden: "ingred77_g.png", amount: 0, discovered: false},
    {id: 107, image_normal: herbs[107], image_golden: "ingred78_g.png", amount: 0, discovered: false},
    {id: 108, image_normal: herbs[108], image_golden: "ingred79_g.png", amount: 0, discovered: false},
    {id: 109, image_normal: herbs[109], image_golden: "ingred80_g.png", amount: 0, discovered: false},

    {id: 110, image_normal: herbs[110], image_golden: "ingred71_g.png", amount: 0, discovered: false},
    {id: 111, image_normal: herbs[111], image_golden: "ingred72_g.png", amount: 0, discovered: false},
    {id: 112, image_normal: herbs[112], image_golden: "ingred73_g.png", amount: 0, discovered: false},
    {id: 113, image_normal: herbs[113], image_golden: "ingred74_g.png", amount: 0, discovered: false},
    {id: 114, image_normal: herbs[114], image_golden: "ingred75_g.png", amount: 0, discovered: false},
    {id: 115, image_normal: herbs[115], image_golden: "ingred76_g.png", amount: 0, discovered: false},
    {id: 116, image_normal: herbs[116], image_golden: "ingred77_g.png", amount: 0, discovered: false},
    {id: 117, image_normal: herbs[117], image_golden: "ingred78_g.png", amount: 0, discovered: false},
    {id: 118, image_normal: herbs[118], image_golden: "ingred79_g.png", amount: 0, discovered: false},
    {id: 119, image_normal: herbs[119], image_golden: "ingred80_g.png", amount: 0, discovered: false},

    {id: 120, image_normal: herbs[120], image_golden: "ingred71_g.png", amount: 0, discovered: false},
    {id: 121, image_normal: herbs[121], image_golden: "ingred72_g.png", amount: 0, discovered: false},
    {id: 122, image_normal: herbs[122], image_golden: "ingred73_g.png", amount: 0, discovered: false},
    {id: 123, image_normal: herbs[123], image_golden: "ingred74_g.png", amount: 0, discovered: false},
    {id: 124, image_normal: herbs[124], image_golden: "ingred75_g.png", amount: 0, discovered: false},
    {id: 125, image_normal: herbs[125], image_golden: "ingred76_g.png", amount: 0, discovered: false},
    {id: 126, image_normal: herbs[126], image_golden: "ingred77_g.png", amount: 0, discovered: false},
    {id: 127, image_normal: herbs[127], image_golden: "ingred78_g.png", amount: 0, discovered: false},
    {id: 128, image_normal: herbs[128], image_golden: "ingred79_g.png", amount: 0, discovered: false},
    {id: 129, image_normal: herbs[129], image_golden: "ingred80_g.png", amount: 0, discovered: false},

    {id: 130, image_normal: herbs[130], image_golden: "ingred71_g.png", amount: 0, discovered: false},
    {id: 131, image_normal: herbs[131], image_golden: "ingred72_g.png", amount: 0, discovered: false},
    {id: 132, image_normal: herbs[132], image_golden: "ingred73_g.png", amount: 0, discovered: false},
    {id: 133, image_normal: herbs[133], image_golden: "ingred74_g.png", amount: 0, discovered: false},
    {id: 134, image_normal: herbs[134], image_golden: "ingred75_g.png", amount: 0, discovered: false},
    {id: 135, image_normal: herbs[135], image_golden: "ingred76_g.png", amount: 0, discovered: false},
    {id: 136, image_normal: herbs[136], image_golden: "ingred77_g.png", amount: 0, discovered: false},
    {id: 137, image_normal: herbs[137], image_golden: "ingred78_g.png", amount: 0, discovered: false},
    {id: 138, image_normal: herbs[138], image_golden: "ingred79_g.png", amount: 0, discovered: false},
    {id: 139, image_normal: herbs[139], image_golden: "ingred80_g.png", amount: 0, discovered: false},

    {id: 140, image_normal: herbs[140], image_golden: "ingred71_g.png", amount: 0, discovered: false},
    {id: 141, image_normal: herbs[141], image_golden: "ingred72_g.png", amount: 0, discovered: false},
    {id: 142, image_normal: herbs[142], image_golden: "ingred73_g.png", amount: 0, discovered: false},
    {id: 143, image_normal: herbs[143], image_golden: "ingred74_g.png", amount: 0, discovered: false},
    {id: 144, image_normal: herbs[144], image_golden: "ingred75_g.png", amount: 0, discovered: false},
    {id: 145, image_normal: herbs[145], image_golden: "ingred76_g.png", amount: 0, discovered: false},
    {id: 146, image_normal: herbs[146], image_golden: "ingred77_g.png", amount: 0, discovered: false},
    {id: 147, image_normal: herbs[147], image_golden: "ingred78_g.png", amount: 0, discovered: false},
    {id: 148, image_normal: herbs[148], image_golden: "ingred79_g.png", amount: 0, discovered: false},
    {id: 149, image_normal: herbs[149], image_golden: "ingred80_g.png", amount: 0, discovered: false},

    {id: 150, image_normal: herbs[150], image_golden: "ingred71_g.png", amount: 0, discovered: false},
    {id: 151, image_normal: herbs[151], image_golden: "ingred72_g.png", amount: 0, discovered: false},
    {id: 152, image_normal: herbs[152], image_golden: "ingred73_g.png", amount: 0, discovered: false},
    {id: 153, image_normal: herbs[153], image_golden: "ingred74_g.png", amount: 0, discovered: false},
    {id: 154, image_normal: herbs[154], image_golden: "ingred75_g.png", amount: 0, discovered: false},
    {id: 155, image_normal: herbs[155], image_golden: "ingred76_g.png", amount: 0, discovered: false},
    {id: 156, image_normal: herbs[156], image_golden: "ingred77_g.png", amount: 0, discovered: false},
    {id: 157, image_normal: herbs[157], image_golden: "ingred78_g.png", amount: 0, discovered: false},
    {id: 158, image_normal: herbs[158], image_golden: "ingred79_g.png", amount: 0, discovered: false},
    {id: 159, image_normal: herbs[159], image_golden: "ingred80_g.png", amount: 0, discovered: false},

    {id: 160, image_normal: herbs[160], image_golden: "ingred71_g.png", amount: 0, discovered: false},
    {id: 161, image_normal: herbs[161], image_golden: "ingred72_g.png", amount: 0, discovered: false},
    {id: 162, image_normal: herbs[162], image_golden: "ingred73_g.png", amount: 0, discovered: false},
    {id: 163, image_normal: herbs[163], image_golden: "ingred74_g.png", amount: 0, discovered: false},
    {id: 164, image_normal: herbs[164], image_golden: "ingred75_g.png", amount: 0, discovered: false},
    {id: 165, image_normal: herbs[165], image_golden: "ingred76_g.png", amount: 0, discovered: false},
    {id: 166, image_normal: herbs[166], image_golden: "ingred77_g.png", amount: 0, discovered: false},
    {id: 167, image_normal: herbs[167], image_golden: "ingred78_g.png", amount: 0, discovered: false},
    {id: 168, image_normal: herbs[168], image_golden: "ingred79_g.png", amount: 0, discovered: false},
    {id: 169, image_normal: herbs[169], image_golden: "ingred80_g.png", amount: 0, discovered: false},

    {id: 170, image_normal: herbs[170], image_golden: "ingred71_g.png", amount: 0, discovered: false},
    {id: 171, image_normal: herbs[171], image_golden: "ingred72_g.png", amount: 0, discovered: false},
    {id: 172, image_normal: herbs[172], image_golden: "ingred73_g.png", amount: 0, discovered: false},
    {id: 173, image_normal: herbs[173], image_golden: "ingred74_g.png", amount: 0, discovered: false},
    {id: 174, image_normal: herbs[174], image_golden: "ingred75_g.png", amount: 0, discovered: false},
    {id: 175, image_normal: herbs[175], image_golden: "ingred76_g.png", amount: 0, discovered: false},
    {id: 176, image_normal: herbs[176], image_golden: "ingred77_g.png", amount: 0, discovered: false},
    {id: 177, image_normal: herbs[177], image_golden: "ingred78_g.png", amount: 0, discovered: false},
    {id: 178, image_normal: herbs[178], image_golden: "ingred79_g.png", amount: 0, discovered: false},
    {id: 179, image_normal: herbs[179], image_golden: "ingred80_g.png", amount: 0, discovered: false},
  ];