import herbs from "../image_assets/HerbImageExport"

export const IngredientData = [
    {id: 1, image_normal: herbs[0], image_golden: "ingred1_g.png", amount: 0, discovered: false},
    {id: 2, image_normal: herbs[1], image_golden: "ingred2_g.png", amount: 0, discovered: false},
    {id: 3, image_normal: herbs[2], image_golden: "ingred3_g.png", amount: 0, discovered: false},
    {id: 4, image_normal: herbs[3], image_golden: "ingred4_g.png", amount: 0, discovered: false},
    {id: 5, image_normal: herbs[4], image_golden: "ingred5_g.png", amount: 0, discovered: false},
    {id: 6, image_normal: herbs[5], image_golden: "ingred6_g.png", amount: 0, discovered: false},
    {id: 7, image_normal: herbs[6], image_golden: "ingred7_g.png", amount: 0, discovered: false},
    {id: 8, image_normal: herbs[7], image_golden: "ingred8_g.png", amount: 0, discovered: false},
    {id: 9, image_normal: herbs[8], image_golden: "ingred9_g.png", amount: 0, discovered: false},
    {id: 10, image_normal: herbs[9], image_golden: "ingred10_g.png", amount: 0, discovered: false},

    {id: 11, image_normal: herbs[10], image_golden: "ingred11_g.png", amount: 0, discovered: false},
    {id: 12, image_normal: herbs[11], image_golden: "ingred12_g.png", amount: 0, discovered: false},
    {id: 13, image_normal: herbs[12], image_golden: "ingred13_g.png", amount: 0, discovered: false},
    {id: 14, image_normal: herbs[13], image_golden: "ingred14_g.png", amount: 0, discovered: false},
    {id: 15, image_normal: herbs[14], image_golden: "ingred15_g.png", amount: 0, discovered: false},
    {id: 16, image_normal: herbs[15], image_golden: "ingred16_g.png", amount: 0, discovered: false},
    {id: 17, image_normal: herbs[16], image_golden: "ingred17_g.png", amount: 0, discovered: false},
    {id: 18, image_normal: herbs[17], image_golden: "ingred18_g.png", amount: 0, discovered: false},
    {id: 19, image_normal: herbs[18], image_golden: "ingred19_g.png", amount: 0, discovered: false},
    {id: 20, image_normal: herbs[19], image_golden: "ingred20_g.png", amount: 0, discovered: false},

    {id: 21, image_normal: herbs[20], image_golden: "ingred21_g.png", amount: 0, discovered: false},
    {id: 22, image_normal: herbs[21], image_golden: "ingred22_g.png", amount: 0, discovered: false},
    {id: 23, image_normal: herbs[22], image_golden: "ingred23_g.png", amount: 0, discovered: false},
    {id: 24, image_normal: herbs[23], image_golden: "ingred24_g.png", amount: 0, discovered: false},
    {id: 25, image_normal: herbs[24], image_golden: "ingred25_g.png", amount: 0, discovered: false},
    {id: 26, image_normal: herbs[25], image_golden: "ingred26_g.png", amount: 0, discovered: false},
    {id: 27, image_normal: herbs[26], image_golden: "ingred27_g.png", amount: 0, discovered: false},
    {id: 28, image_normal: herbs[27], image_golden: "ingred28_g.png", amount: 0, discovered: false},
    {id: 29, image_normal: herbs[28], image_golden: "ingred29_g.png", amount: 0, discovered: false},
    {id: 30, image_normal: herbs[29], image_golden: "ingred30_g.png", amount: 0, discovered: false},

    {id: 31, image_normal: herbs[30], image_golden: "ingred31_g.png", amount: 0, discovered: false},
    {id: 32, image_normal: herbs[31], image_golden: "ingred32_g.png", amount: 0, discovered: false},
    {id: 33, image_normal: herbs[32], image_golden: "ingred33_g.png", amount: 0, discovered: false},
    {id: 34, image_normal: herbs[33], image_golden: "ingred34_g.png", amount: 0, discovered: false},
    {id: 35, image_normal: herbs[34], image_golden: "ingred35_g.png", amount: 0, discovered: false},
    {id: 36, image_normal: herbs[35], image_golden: "ingred36_g.png", amount: 0, discovered: false},
    {id: 37, image_normal: herbs[36], image_golden: "ingred37_g.png", amount: 0, discovered: false},
    {id: 38, image_normal: herbs[37], image_golden: "ingred38_g.png", amount: 0, discovered: false},
    {id: 39, image_normal: herbs[38], image_golden: "ingred39_g.png", amount: 0, discovered: false},
    {id: 40, image_normal: herbs[39], image_golden: "ingred40_g.png", amount: 0, discovered: false},

    {id: 41, image_normal: herbs[40], image_golden: "ingred41_g.png", amount: 0, discovered: false},
    {id: 42, image_normal: herbs[41], image_golden: "ingred42_g.png", amount: 0, discovered: false},
    {id: 43, image_normal: herbs[42], image_golden: "ingred43_g.png", amount: 0, discovered: false},
    {id: 44, image_normal: herbs[43], image_golden: "ingred44_g.png", amount: 0, discovered: false},
    {id: 45, image_normal: herbs[44], image_golden: "ingred45_g.png", amount: 0, discovered: false},
    {id: 46, image_normal: herbs[45], image_golden: "ingred46_g.png", amount: 0, discovered: false},
    {id: 47, image_normal: herbs[46], image_golden: "ingred47_g.png", amount: 0, discovered: false},
    {id: 48, image_normal: herbs[47], image_golden: "ingred48_g.png", amount: 0, discovered: false},
    {id: 49, image_normal: herbs[48], image_golden: "ingred49_g.png", amount: 0, discovered: false},
    {id: 50, image_normal: herbs[49], image_golden: "ingred50_g.png", amount: 0, discovered: false},

    {id: 51, image_normal: herbs[50], image_golden: "ingred51_g.png", amount: 0, discovered: false},
    {id: 52, image_normal: herbs[51], image_golden: "ingred52_g.png", amount: 0, discovered: false},
    {id: 53, image_normal: herbs[52], image_golden: "ingred53_g.png", amount: 0, discovered: false},
    {id: 54, image_normal: herbs[53], image_golden: "ingred54_g.png", amount: 0, discovered: false},
    {id: 55, image_normal: herbs[54], image_golden: "ingred55_g.png", amount: 0, discovered: false},
    {id: 56, image_normal: herbs[55], image_golden: "ingred56_g.png", amount: 0, discovered: false},
    {id: 57, image_normal: herbs[56], image_golden: "ingred57_g.png", amount: 0, discovered: false},
    {id: 58, image_normal: herbs[57], image_golden: "ingred58_g.png", amount: 0, discovered: false},
    {id: 59, image_normal: herbs[58], image_golden: "ingred59_g.png", amount: 0, discovered: false},
    {id: 60, image_normal: herbs[59], image_golden: "ingred60_g.png", amount: 0, discovered: false},

    {id: 61, image_normal: herbs[60], image_golden: "ingred61_g.png", amount: 0, discovered: false},
    {id: 62, image_normal: herbs[61], image_golden: "ingred62_g.png", amount: 0, discovered: false},
    {id: 63, image_normal: herbs[62], image_golden: "ingred63_g.png", amount: 0, discovered: false},
    {id: 64, image_normal: herbs[63], image_golden: "ingred64_g.png", amount: 0, discovered: false},
    {id: 65, image_normal: herbs[64], image_golden: "ingred65_g.png", amount: 0, discovered: false},
    {id: 66, image_normal: herbs[65], image_golden: "ingred66_g.png", amount: 0, discovered: false},
    {id: 67, image_normal: herbs[66], image_golden: "ingred67_g.png", amount: 0, discovered: false},
    {id: 68, image_normal: herbs[67], image_golden: "ingred68_g.png", amount: 0, discovered: false},
     
  ];