import herbs from "../image_assets/HerbImageExport"
import goldenHerbs from "../image_assets/HerbImageGoldExport"

export const IngredientData = [
    {id: 0, image_normal: herbs[0], image_golden: goldenHerbs[0], amount: 0, discovered: false},
    {id: 1, image_normal: herbs[1], image_golden: goldenHerbs[1], amount: 0, discovered: false},
    {id: 2, image_normal: herbs[2], image_golden: goldenHerbs[2], amount: 0, discovered: false},
    {id: 3, image_normal: herbs[3], image_golden: goldenHerbs[3], amount: 0, discovered: false},
    {id: 4, image_normal: herbs[4], image_golden: goldenHerbs[4], amount: 0, discovered: false},
    {id: 5, image_normal: herbs[5], image_golden: goldenHerbs[5], amount: 0, discovered: false},
    {id: 6, image_normal: herbs[6], image_golden: goldenHerbs[6], amount: 0, discovered: false},
    {id: 7, image_normal: herbs[7], image_golden: goldenHerbs[7], amount: 0, discovered: false},
    {id: 8, image_normal: herbs[8], image_golden: goldenHerbs[8], amount: 0, discovered: false},
    {id: 9, image_normal: herbs[9], image_golden: goldenHerbs[9], amount: 0, discovered: false},

    {id: 10, image_normal: herbs[10], image_golden: goldenHerbs[10], amount: 0, discovered: false},
    {id: 11, image_normal: herbs[11], image_golden: goldenHerbs[11], amount: 0, discovered: false},
    {id: 12, image_normal: herbs[12], image_golden: goldenHerbs[12], amount: 0, discovered: false},
    {id: 13, image_normal: herbs[13], image_golden: goldenHerbs[13], amount: 0, discovered: false},
    {id: 14, image_normal: herbs[14], image_golden: goldenHerbs[14], amount: 0, discovered: false},
    {id: 15, image_normal: herbs[15], image_golden: goldenHerbs[15], amount: 0, discovered: false},
    {id: 16, image_normal: herbs[16], image_golden: goldenHerbs[16], amount: 0, discovered: false},
    {id: 17, image_normal: herbs[17], image_golden: goldenHerbs[17], amount: 0, discovered: false},
    {id: 18, image_normal: herbs[18], image_golden: goldenHerbs[18], amount: 0, discovered: false},
    {id: 19, image_normal: herbs[19], image_golden: goldenHerbs[19], amount: 0, discovered: false},

    {id: 20, image_normal: herbs[20], image_golden: goldenHerbs[20], amount: 0, discovered: false},
    {id: 21, image_normal: herbs[21], image_golden: goldenHerbs[21], amount: 0, discovered: false},
    {id: 22, image_normal: herbs[22], image_golden: goldenHerbs[22], amount: 0, discovered: false},
    {id: 23, image_normal: herbs[23], image_golden: goldenHerbs[23], amount: 0, discovered: false},
    {id: 24, image_normal: herbs[24], image_golden: goldenHerbs[24], amount: 0, discovered: false},
    {id: 25, image_normal: herbs[25], image_golden: goldenHerbs[25], amount: 0, discovered: false},
    {id: 26, image_normal: herbs[26], image_golden: goldenHerbs[26], amount: 0, discovered: false},
    {id: 27, image_normal: herbs[27], image_golden: goldenHerbs[27], amount: 0, discovered: false},
    {id: 28, image_normal: herbs[28], image_golden: goldenHerbs[28], amount: 0, discovered: false},
    {id: 29, image_normal: herbs[29], image_golden: goldenHerbs[29], amount: 0, discovered: false},

    {id: 30, image_normal: herbs[30], image_golden: goldenHerbs[30], amount: 0, discovered: false},
    {id: 31, image_normal: herbs[31], image_golden: goldenHerbs[31], amount: 0, discovered: false},
    {id: 32, image_normal: herbs[32], image_golden: goldenHerbs[32], amount: 0, discovered: false},
    {id: 33, image_normal: herbs[33], image_golden: goldenHerbs[33], amount: 0, discovered: false},
    {id: 34, image_normal: herbs[34], image_golden: goldenHerbs[34], amount: 0, discovered: false},
    {id: 35, image_normal: herbs[35], image_golden: goldenHerbs[35], amount: 0, discovered: false},
    {id: 36, image_normal: herbs[36], image_golden: goldenHerbs[36], amount: 0, discovered: false},
    {id: 37, image_normal: herbs[37], image_golden: goldenHerbs[37], amount: 0, discovered: false},
    {id: 38, image_normal: herbs[38], image_golden: goldenHerbs[38], amount: 0, discovered: false},
    {id: 39, image_normal: herbs[39], image_golden: goldenHerbs[39], amount: 0, discovered: false},

    {id: 40, image_normal: herbs[40], image_golden: goldenHerbs[40], amount: 0, discovered: false},
    {id: 41, image_normal: herbs[41], image_golden: goldenHerbs[41], amount: 0, discovered: false},
    {id: 42, image_normal: herbs[42], image_golden: goldenHerbs[42], amount: 0, discovered: false},
    {id: 43, image_normal: herbs[43], image_golden: goldenHerbs[43], amount: 0, discovered: false},
    {id: 44, image_normal: herbs[44], image_golden: goldenHerbs[44], amount: 0, discovered: false},
    {id: 45, image_normal: herbs[45], image_golden: goldenHerbs[45], amount: 0, discovered: false},
    {id: 46, image_normal: herbs[46], image_golden: goldenHerbs[46], amount: 0, discovered: false},
    {id: 47, image_normal: herbs[47], image_golden: goldenHerbs[47], amount: 0, discovered: false},
    {id: 48, image_normal: herbs[48], image_golden: goldenHerbs[48], amount: 0, discovered: false},
    {id: 49, image_normal: herbs[49], image_golden: goldenHerbs[49], amount: 0, discovered: false},

    {id: 50, image_normal: herbs[50], image_golden: goldenHerbs[50], amount: 0, discovered: false},
    {id: 51, image_normal: herbs[51], image_golden: goldenHerbs[51], amount: 0, discovered: false},
    {id: 52, image_normal: herbs[52], image_golden: goldenHerbs[52], amount: 0, discovered: false},
    {id: 53, image_normal: herbs[53], image_golden: goldenHerbs[53], amount: 0, discovered: false},
    {id: 54, image_normal: herbs[54], image_golden: goldenHerbs[54], amount: 0, discovered: false},
    {id: 55, image_normal: herbs[55], image_golden: goldenHerbs[55], amount: 0, discovered: false},
    {id: 56, image_normal: herbs[56], image_golden: goldenHerbs[56], amount: 0, discovered: false},
    {id: 57, image_normal: herbs[57], image_golden: goldenHerbs[57], amount: 0, discovered: false},
    {id: 58, image_normal: herbs[58], image_golden: goldenHerbs[58], amount: 0, discovered: false},
    {id: 59, image_normal: herbs[59], image_golden: goldenHerbs[59], amount: 0, discovered: false},

    {id: 60, image_normal: herbs[60], image_golden: goldenHerbs[60], amount: 0, discovered: false},
    {id: 61, image_normal: herbs[61], image_golden: goldenHerbs[61], amount: 0, discovered: false},
    {id: 62, image_normal: herbs[62], image_golden: goldenHerbs[62], amount: 0, discovered: false},
    {id: 63, image_normal: herbs[63], image_golden: goldenHerbs[63], amount: 0, discovered: false},
    {id: 64, image_normal: herbs[64], image_golden: goldenHerbs[64], amount: 0, discovered: false},
    {id: 65, image_normal: herbs[65], image_golden: goldenHerbs[65], amount: 0, discovered: false},
    {id: 66, image_normal: herbs[66], image_golden: goldenHerbs[66], amount: 0, discovered: false},
    {id: 67, image_normal: herbs[67], image_golden: goldenHerbs[67], amount: 0, discovered: false},
    {id: 68, image_normal: herbs[68], image_golden: goldenHerbs[68], amount: 0, discovered: false},
    {id: 69, image_normal: herbs[69], image_golden: goldenHerbs[69], amount: 0, discovered: false},
     
    {id: 70, image_normal: herbs[70], image_golden: goldenHerbs[70], amount: 0, discovered: false},
    {id: 71, image_normal: herbs[71], image_golden: goldenHerbs[71], amount: 0, discovered: false},
    {id: 72, image_normal: herbs[72], image_golden: goldenHerbs[72], amount: 0, discovered: false},
    {id: 73, image_normal: herbs[73], image_golden: goldenHerbs[73], amount: 0, discovered: false},
    {id: 74, image_normal: herbs[74], image_golden: goldenHerbs[74], amount: 0, discovered: false},
    {id: 75, image_normal: herbs[75], image_golden: goldenHerbs[75], amount: 0, discovered: false},
    {id: 76, image_normal: herbs[76], image_golden: goldenHerbs[76], amount: 0, discovered: false},
    {id: 77, image_normal: herbs[77], image_golden: goldenHerbs[77], amount: 0, discovered: false},
    {id: 78, image_normal: herbs[78], image_golden: goldenHerbs[78], amount: 0, discovered: false},
    {id: 79, image_normal: herbs[79], image_golden: goldenHerbs[79], amount: 0, discovered: false},

    {id: 80, image_normal: herbs[80], image_golden: goldenHerbs[80], amount: 0, discovered: false},
    {id: 81, image_normal: herbs[81], image_golden: goldenHerbs[81], amount: 0, discovered: false},
    {id: 82, image_normal: herbs[82], image_golden: goldenHerbs[82], amount: 0, discovered: false},
    {id: 83, image_normal: herbs[83], image_golden: goldenHerbs[83], amount: 0, discovered: false},
    {id: 84, image_normal: herbs[84], image_golden: goldenHerbs[84], amount: 0, discovered: false},
    {id: 85, image_normal: herbs[85], image_golden: goldenHerbs[85], amount: 0, discovered: false},
    {id: 86, image_normal: herbs[86], image_golden: goldenHerbs[86], amount: 0, discovered: false},
    {id: 87, image_normal: herbs[87], image_golden: goldenHerbs[87], amount: 0, discovered: false},
    {id: 88, image_normal: herbs[88], image_golden: goldenHerbs[88], amount: 0, discovered: false},
    {id: 89, image_normal: herbs[89], image_golden: goldenHerbs[89], amount: 0, discovered: false},

    {id: 90, image_normal: herbs[90], image_golden: goldenHerbs[90], amount: 0, discovered: false},
    {id: 91, image_normal: herbs[91], image_golden: goldenHerbs[91], amount: 0, discovered: false},
    {id: 92, image_normal: herbs[92], image_golden: goldenHerbs[92], amount: 0, discovered: false},
    {id: 93, image_normal: herbs[93], image_golden: goldenHerbs[93], amount: 0, discovered: false},
    {id: 94, image_normal: herbs[94], image_golden: goldenHerbs[94], amount: 0, discovered: false},
    {id: 95, image_normal: herbs[95], image_golden: goldenHerbs[95], amount: 0, discovered: false},
    {id: 96, image_normal: herbs[96], image_golden: goldenHerbs[96], amount: 0, discovered: false},
    {id: 97, image_normal: herbs[97], image_golden: goldenHerbs[97], amount: 0, discovered: false},
    {id: 98, image_normal: herbs[98], image_golden: goldenHerbs[98], amount: 0, discovered: false},
    {id: 99, image_normal: herbs[99], image_golden: goldenHerbs[99], amount: 0, discovered: false},

    {id: 100, image_normal: herbs[100], image_golden: goldenHerbs[100], amount: 0, discovered: false},
    {id: 101, image_normal: herbs[101], image_golden: goldenHerbs[101], amount: 0, discovered: false},
    {id: 102, image_normal: herbs[102], image_golden: goldenHerbs[102], amount: 0, discovered: false},
    {id: 103, image_normal: herbs[103], image_golden: goldenHerbs[103], amount: 0, discovered: false},
    {id: 104, image_normal: herbs[104], image_golden: goldenHerbs[104], amount: 0, discovered: false},
    {id: 105, image_normal: herbs[105], image_golden: goldenHerbs[105], amount: 0, discovered: false},
    {id: 106, image_normal: herbs[106], image_golden: goldenHerbs[106], amount: 0, discovered: false},
    {id: 107, image_normal: herbs[107], image_golden: goldenHerbs[107], amount: 0, discovered: false},
    {id: 108, image_normal: herbs[108], image_golden: goldenHerbs[108], amount: 0, discovered: false},
    {id: 109, image_normal: herbs[109], image_golden: goldenHerbs[109], amount: 0, discovered: false},

    {id: 110, image_normal: herbs[110], image_golden: goldenHerbs[110], amount: 0, discovered: false},
    {id: 111, image_normal: herbs[111], image_golden: goldenHerbs[111], amount: 0, discovered: false},
    {id: 112, image_normal: herbs[112], image_golden: goldenHerbs[112], amount: 0, discovered: false},
    {id: 113, image_normal: herbs[113], image_golden: goldenHerbs[113], amount: 0, discovered: false},
    {id: 114, image_normal: herbs[114], image_golden: goldenHerbs[114], amount: 0, discovered: false},
    {id: 115, image_normal: herbs[115], image_golden: goldenHerbs[115], amount: 0, discovered: false},
    {id: 116, image_normal: herbs[116], image_golden: goldenHerbs[116], amount: 0, discovered: false},
    {id: 117, image_normal: herbs[117], image_golden: goldenHerbs[117], amount: 0, discovered: false},
    {id: 118, image_normal: herbs[118], image_golden: goldenHerbs[118], amount: 0, discovered: false},
    {id: 119, image_normal: herbs[119], image_golden: goldenHerbs[119], amount: 0, discovered: false},

    {id: 120, image_normal: herbs[120], image_golden: goldenHerbs[120], amount: 0, discovered: false},
    {id: 121, image_normal: herbs[121], image_golden: goldenHerbs[121], amount: 0, discovered: false},
    {id: 122, image_normal: herbs[122], image_golden: goldenHerbs[122], amount: 0, discovered: false},
    {id: 123, image_normal: herbs[123], image_golden: goldenHerbs[123], amount: 0, discovered: false},
    {id: 124, image_normal: herbs[124], image_golden: goldenHerbs[124], amount: 0, discovered: false},
    {id: 125, image_normal: herbs[125], image_golden: goldenHerbs[125], amount: 0, discovered: false},
    {id: 126, image_normal: herbs[126], image_golden: goldenHerbs[126], amount: 0, discovered: false},
    {id: 127, image_normal: herbs[127], image_golden: goldenHerbs[127], amount: 0, discovered: false},
    {id: 128, image_normal: herbs[128], image_golden: goldenHerbs[128], amount: 0, discovered: false},
    {id: 129, image_normal: herbs[129], image_golden: goldenHerbs[129], amount: 0, discovered: false},

    {id: 130, image_normal: herbs[130], image_golden: goldenHerbs[130], amount: 0, discovered: false},
    {id: 131, image_normal: herbs[131], image_golden: goldenHerbs[131], amount: 0, discovered: false},
    {id: 132, image_normal: herbs[132], image_golden: goldenHerbs[132], amount: 0, discovered: false},
    {id: 133, image_normal: herbs[133], image_golden: goldenHerbs[133], amount: 0, discovered: false},
    {id: 134, image_normal: herbs[134], image_golden: goldenHerbs[134], amount: 0, discovered: false},
    {id: 135, image_normal: herbs[135], image_golden: goldenHerbs[135], amount: 0, discovered: false},
    {id: 136, image_normal: herbs[136], image_golden: goldenHerbs[136], amount: 0, discovered: false},
    {id: 137, image_normal: herbs[137], image_golden: goldenHerbs[137], amount: 0, discovered: false},
    {id: 138, image_normal: herbs[138], image_golden: goldenHerbs[138], amount: 0, discovered: false},
    {id: 139, image_normal: herbs[139], image_golden: goldenHerbs[139], amount: 0, discovered: false},

    {id: 140, image_normal: herbs[140], image_golden: goldenHerbs[140], amount: 0, discovered: false},
    {id: 141, image_normal: herbs[141], image_golden: goldenHerbs[141], amount: 0, discovered: false},
    {id: 142, image_normal: herbs[142], image_golden: goldenHerbs[142], amount: 0, discovered: false},
    {id: 143, image_normal: herbs[143], image_golden: goldenHerbs[143], amount: 0, discovered: false},
    {id: 144, image_normal: herbs[144], image_golden: goldenHerbs[144], amount: 0, discovered: false},
    {id: 145, image_normal: herbs[145], image_golden: goldenHerbs[145], amount: 0, discovered: false},
    {id: 146, image_normal: herbs[146], image_golden: goldenHerbs[146], amount: 0, discovered: false},
    {id: 147, image_normal: herbs[147], image_golden: goldenHerbs[147], amount: 0, discovered: false},
    {id: 148, image_normal: herbs[148], image_golden: goldenHerbs[148], amount: 0, discovered: false},
    {id: 149, image_normal: herbs[149], image_golden: goldenHerbs[149], amount: 0, discovered: false},

    {id: 150, image_normal: herbs[150], image_golden: goldenHerbs[150], amount: 0, discovered: false},
    {id: 151, image_normal: herbs[151], image_golden: goldenHerbs[151], amount: 0, discovered: false},
    {id: 152, image_normal: herbs[152], image_golden: goldenHerbs[152], amount: 0, discovered: false},
    {id: 153, image_normal: herbs[153], image_golden: goldenHerbs[153], amount: 0, discovered: false},
    {id: 154, image_normal: herbs[154], image_golden: goldenHerbs[154], amount: 0, discovered: false},
    {id: 155, image_normal: herbs[155], image_golden: goldenHerbs[155], amount: 0, discovered: false},
    {id: 156, image_normal: herbs[156], image_golden: goldenHerbs[156], amount: 0, discovered: false},
    {id: 157, image_normal: herbs[157], image_golden: goldenHerbs[157], amount: 0, discovered: false},
    {id: 158, image_normal: herbs[158], image_golden: goldenHerbs[158], amount: 0, discovered: false},
    {id: 159, image_normal: herbs[159], image_golden: goldenHerbs[159], amount: 0, discovered: false},

    {id: 160, image_normal: herbs[160], image_golden: goldenHerbs[160], amount: 0, discovered: false},
    {id: 161, image_normal: herbs[161], image_golden: goldenHerbs[161], amount: 0, discovered: false},
    {id: 162, image_normal: herbs[162], image_golden: goldenHerbs[162], amount: 0, discovered: false},
    {id: 163, image_normal: herbs[163], image_golden: goldenHerbs[163], amount: 0, discovered: false},
    {id: 164, image_normal: herbs[164], image_golden: goldenHerbs[164], amount: 0, discovered: false},
    {id: 165, image_normal: herbs[165], image_golden: goldenHerbs[165], amount: 0, discovered: false},
    {id: 166, image_normal: herbs[166], image_golden: goldenHerbs[166], amount: 0, discovered: false},
    {id: 167, image_normal: herbs[167], image_golden: goldenHerbs[167], amount: 0, discovered: false},
    {id: 168, image_normal: herbs[168], image_golden: goldenHerbs[168], amount: 0, discovered: false},
    {id: 169, image_normal: herbs[169], image_golden: goldenHerbs[169], amount: 0, discovered: false},

    {id: 170, image_normal: herbs[170], image_golden: goldenHerbs[170], amount: 0, discovered: false},
    {id: 171, image_normal: herbs[171], image_golden: goldenHerbs[171], amount: 0, discovered: false},
    {id: 172, image_normal: herbs[172], image_golden: goldenHerbs[172], amount: 0, discovered: false},
    {id: 173, image_normal: herbs[173], image_golden: goldenHerbs[173], amount: 0, discovered: false},
    {id: 174, image_normal: herbs[174], image_golden: goldenHerbs[174], amount: 0, discovered: false},
    {id: 175, image_normal: herbs[175], image_golden: goldenHerbs[175], amount: 0, discovered: false},
    {id: 176, image_normal: herbs[176], image_golden: goldenHerbs[176], amount: 0, discovered: false},
    {id: 177, image_normal: herbs[177], image_golden: goldenHerbs[177], amount: 0, discovered: false},
    {id: 178, image_normal: herbs[178], image_golden: goldenHerbs[178], amount: 0, discovered: false},
    {id: 179, image_normal: herbs[179], image_golden: goldenHerbs[179], amount: 0, discovered: false},
  ];